name: mbespc
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - GDAL==3.8.3
  - tiledb==2.19.1
  - numpy==1.26.4
  - pyproj==3.6.1
  - pdal=2.6.3
  - python-pdal==3.3.0
  - rasterio==1.3.9
  - pip
  - pip:
    - -r requirements.txt
