name: Tests

on:
  push:
    #branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: latest
          cache: true

      - name: Install dependencies
        run: pixi install

      - name: Run tests
        run: pixi run pytest